apiVersion: v1
kind: ConfigMap
metadata:
  name: app
data:
  SERVER_PORT: "1234"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-volume
data:
  config.json: |
    {
      "name":"app",
      "version":"v1.0.1"
    }
