---
apiVersion: skaffold/v2beta11
kind: Config

build:
  artifacts:
    - image: app
      context: ./app
      docker:
        dockerfile: Dockerfile
        target: runtime
    - image: internal-api
      context: ./internal-api
      docker:
        dockerfile: Dockerfile
        target: runtime

deploy:
  helm:
    releases:
      - name: local-test
        chartPath: ./k8s
        namespace: local
        createNamespace: true
        # helmのvalues.yamlに定義しているイメージ名を上書きする
        artifactOverrides:
          app.image: app
          internalApi.image: internal-api
