services:
  app:
    name: app
    image: app
    type: NodePort
    targetPort: 1234
    nodePort: 30001
    replicas: 3
    configMap:
      data:
        INTERNAL_API_HOST: "http://internal-api"
        INTERNAL_API_PORT: "80"
  internalApi:
    name: internal-api
    image: internal-api
    type: ClusterIP
    targetPort: 1235
    replicas: 3
    configMap:
      data:
        DB_HOST: "mysql"
        DB_USER: "root"
        DB_PASSWORD: "root"
        DB_NAME: "test"

mysql:
  auth:
    # 練習リポジトリなのでベタ書きでいいけれど、
    # 本来はこういうのは良くない
    rootPassword: password

  initdbScripts:
    testdb.sql: |
      show databases;
    createdb.sql: |-
      CREATE DATABASE IF NOT EXISTS test;
      use test;

      CREATE TABLE IF NOT EXISTS `users` (
          PRIMARY KEY (id),
          id    INT(5)       NOT NULL,
          name  VARCHAR(255) NOT NULL,
          email VARCHAR(255) NOT NULL
      );

      INSERT INTO `users` (
        id, name, email
      ) VALUES (
        1, 'taro', 'taro@example.com'
      );
