version: '3'

tasks:
  setup:
    desc: "開発環境を構築する"
    deps:
      - install:apt
      - install:docker-compose
      - install:neovim
      - install:shfmt
      - install:fzf
      - install:go
      - install:java
      - install:mmv
      - install:direnv
    cmds:
      - task: copy:netrc
      - task: copy:ssh-config
      - task: install:ghq
      - task: config:git
      - task: config:dotfiles
      - task: config:fish
      - task: config:docker
      - task: config:default-shell
      - task: install:nim
      - task: install:ripgrep
      - task: install:gopls
      - task: install:anyenv
      - task: install:nodenv
      - task: install:clojure
      - task: install:lein

  build:app:
    desc: "appコンテナのイメージをビルドする"
    dir: app
    cmds:
      - docker build -t app .
