---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
  annotations:
    # なぜこのリソースが存在するのか不明になったときに問い合わせる目的
    owner: {{ $.Values.owner }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: {{ $.Values.app.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ $.Values.app.port }}
          env:
            - name: SERVER_PORT
              value: "{{ $.Values.app.port }}"
          envFrom:
            - configMapRef:
                name: app
            - secretRef:
                name: common
          resources:
            requests:
              memory: 25Mi
              cpu: 100m
            limits:
              memory: 100Mi
              cpu: 300m
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: {{ $.Values.app.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: app-volume
              mountPath: /etc/app
      volumes:
        - name: app-volume
          configMap:
            name: app-volume

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-api
  labels:
    app: internal-api
  annotations:
    # なぜこのリソースが存在するのか不明になったときに問い合わせる目的
    owner: {{ $.Values.owner }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: internal-api
  template:
    metadata:
      labels:
        app: internal-api
    spec:
      containers:
        - name: internal-api
          image: {{ $.Values.internalApi.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ $.Values.internalApi.port }}
          env:
            - name: SERVER_PORT
              value: "{{ $.Values.internalApi.port }}"
          envFrom:
            - secretRef:
                name: common
          resources:
            requests:
              memory: 50Mi
              cpu: 100m
            limits:
              memory: 100Mi
              cpu: 300m
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: {{ $.Values.internalApi.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
