---
# ノードのアップグレード等の理由でPodが停止される場合に残しておくPod数を指定する
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pdb
spec:
  minAvailable: 1
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: ["app", "internal-api"]
