services:
  app:
    name: app
    type: NodePort
    targetPort: 1234
    nodePort: 30001
    replicas: 3
    configMap:
      data:
        INTERNAL_API_HOST: "http://internal-api"
        INTERNAL_API_PORT: "80"
  internalApi:
    name: internal-api
    type: ClusterIP
    targetPort: 1235
    replicas: 3
    configMap:
      data:
        NONE: "1"