= 06_skaffold
:toc: left
:sectnums:

単純にSkaffoldを入れるだけだと、ビルドされたイメージを使ってくれない。
HelmのValuesを上書きする形でChartに取り込むことで、ビルドされたイメージを使うようにする。

https://skaffold.dev/docs/pipeline-stages/deployers/helm/

`skaffold dev` をTaskfile.ymlに書こうかと思ったけれど、どうもCtrl-Cで実行してる
タスクを停止したときに、うまくシグナルがskaffoldに伝わらないらしく、skaffoldが自
動でやってくれるリソースの後始末をやってくれなかった。よって、しかたなく
`skaffold dev` はTaskには定義せずに手打ちする。

== 用語

=== Skaffold

Kubernetesの事実上デファクトスタンダードになっているパッケージマネージャ

https://github.com/helm/helm

=== Chart

Kubernetestのリソース定義をまとめたもの。
ChartにKubernetesのServiceやDeployment、ConfigMapなどの各種リソースを定義す
る。
これらはGoのテンプレート構文を利用した `templates` を書いて表現する。
テンプレート内に展開される文字は `values.yaml` に書く。

Chartのユーザはコマンドラインで設定値を上書きしたり、追加で `values.yaml` を指定
して上書きしたりしてインストールする。

=== Release

TBD

== 構成

|======
| ディレクトリ | 説明
| app | シンプルなGoのWebサーバ。1234ポートをlistenする
| internal-api | 内部API。1235ポートをlistenする
| k8s | HelmのChartディレクトリ
|======

== 動作方法

taskコマンドを使ってKubernetesを操作します。
処理内容についてはTaskfile.ymlを見てください。

.appコンテナのビルドとKubernetesクラスタへの適用
[source,bash]
----
skaffold dev
----

この状態でskaffoldが待機状態になる。
ためしにこの状態で app/main.nim を更新してみると、自動でコンテナが再ビルドされる
ことが確認できる。

.クラスタの状態確認と、起動しているPodsへの疎通確認
[source,bash]
----
task check
----

クラスタに適用した各種リソースは、 `skaffold dev` を停止するときに自動で削除され
るはずだが、削除されなかった場合は以下のコマンドで後始末できる。

.クラスタに作った各種リソースの削除
[source,bash]
----
task k8s:clear
----
