version: '3'

vars:
  NAMESPACE: local
  HELM_VERSION: v3.5.0
  RELEASE_NAME: local-test

tasks:
  setup:
    desc: "必要な外部コマンドをインストールする"
    cmds:
      - task: setup:helm
      - task: setup:skaffold

  setup:helm:
    desc: "helmをインストールする"
    dir: /usr/local/src
    cmds:
      - sudo install -m 0755 -o $USER -g $USER -d helm/{{.HELM_VERSION}}
      - |
        set -eu

        cd helm/{{.HELM_VERSION}}
        wget https://get.helm.sh/helm-{{.HELM_VERSION}}-linux-amd64.tar.gz
        tar xzf helm-{{.HELM_VERSION}}-linux-amd64.tar.gz
        chmod +x linux-amd64/helm
        sudo ln -sfn $PWD/linux-amd64/helm /usr/local/bin/helm
    status:
      - which helm

  setup:skaffold:
    desc: "skaffoldをインストールする"
    dir: /tmp
    cmds:
      - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
      - sudo install -m 0755 skaffold /usr/local/bin/
    status:
      - which skaffold

  docker:build:all:
    desc: "必要なすべてのコンテナのイメージをビルドする"
    cmds:
      - task: docker:build:app
      - task: docker:build:internal-api

  docker:build:app:
    desc: "appコンテナのイメージをビルドする"
    dir: app
    cmds:
      - docker build -t app .

  docker:build:internal-api:
    desc: "internal-apiコンテナのイメージをビルドする"
    dir: internal-api
    cmds:
      - docker build -t internal-api .

  k8s:create:namespace:
    desc: "名前空間を作成する"
    cmds:
      - kubectl create namespace {{.NAMESPACE}}
    status:
      - kubectl get namespace {{.NAMESPACE}}

  k8s:delete:namespace:
    desc: "名前空間を削除する"
    cmds:
      - kubectl delete namespace {{.NAMESPACE}}

  k8s:apply:
    desc: "マニフェストファイルをKubernetesクラスタに適用する"
    deps:
      - task: k8s:create:namespace
    cmds:
      - helm install --debug --dry-run {{.RELEASE_NAME}} ./k8s

  k8s:apply:run:
    desc: "マニフェストファイルをKubernetesクラスタに適用する"
    deps:
      - task: k8s:create:namespace
    cmds:
      - task: helm:install
      - sleep 3
      - task: k8s:get:all

  k8s:clear:
    desc: "作成したリソースを削除する"
    cmds:
      - task: k8s:delete:namespace
      - task: k8s:get:all
      - task: helm:uninstall
      - helm list

  k8s:get:all:
    desc: "名前空間配下のすべてのリソースを表示する"
    cmds:
      - kubectl get all -n {{.NAMESPACE}}

  helm:install:
    desc: "チャートをインストールする"
    cmds:
      - helm install -n {{.NAMESPACE}} {{.RELEASE_NAME}} ./k8s

  helm:uninstall:
    desc: "チャートをアンインストールする"
    cmds:
      - helm uninstall -n {{.NAMESPACE}} {{.RELEASE_NAME}}

  run:
    desc: "appコンテナをビルドしてKubernetesクラスタに適用する"
    cmds:
      - task: docker:build:all
      - task: k8s:apply:run

  check:
    desc: "Podsとの疎通確認を行う"
    cmds:
      - kubectl get pods -n {{.NAMESPACE}}
      - curl http://localhost:30001
