apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: app # 手元でビルドした app コンテナのイメージ名
        imagePullPolicy: IfNotPresent # 先にローカルにimageが存在するかをチェックする
        ports:
        - containerPort: 1234 # appコンテナのlistenポート
        envFrom:
        - configMapRef:
            name: app
        volumeMounts:
        - name: app-volume
          mountPath: /etc/app
      volumes:
        # configmap.yamlで作成するConfigMapを設定
        - name: app-volume
          configMap:
            name: app-volume

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-api
  labels:
    app: internal-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: internal-api
  template:
    metadata:
      labels:
        app: internal-api
    spec:
      containers:
      - name: internal-api
        image: internal-api # 手元でビルドした app コンテナのイメージ名
        imagePullPolicy: IfNotPresent # 先にローカルにimageが存在するかをチェックする
        ports:
        - containerPort: 1235 # appコンテナのlistenポート
        env:
        - name: SERVER_PORT
          value: "1235"