= 07_monitoring
:toc: left
:sectnums:

アプリケーションのログ確認は `kubectl logs` コマンドで実施できる。
しかし、ポッドが複数起動して、開発中で何度もデバッグをしないといけない時に、
いちいち上記のコマンドを入力するのは手間。

ということでTUIでKubernetesクラスタの状態を確認できるように
https://github.com/derailed/k9s[k9s]というツールを導入する。

インストール設定はTaskfile.ymlに書いているので、 `task setup` でインストールされる。

インストール後は `skaffold dev` で環境を起動した後に、別端末を開いて `k9s` と実行するだけ。
あとは画面に表示されるヘルプを見ながら操作をすれば良い。
（おまけで `task ui` でも実行できるようにした)

これでkubectlコマンドともおさらばできるかもしれない。

== 余談

当初はgrafanaが提供するloki-stackというHelmチャートをインストールして、ブラウザでログを確認できるようにしたかった。

が、ローカル開発で使うには大掛かりすぎるのでやっぱりやめた。作りかけのものはブランチに残している。
必要になったらブランチから掘り起こせば良いだろう。

== 用語

なし

== 構成

|======
| ディレクトリ | 説明
| app | シンプルなGoのWebサーバ。1234ポートをlistenする
| internal-api | 内部API。1235ポートをlistenする
| k8s | HelmのChartディレクトリ
|======

== 動作方法

taskコマンドを使ってKubernetesを操作します。
処理内容についてはTaskfile.ymlを見てください。

.appコンテナのビルドとKubernetesクラスタへの適用
[source,bash]
----
skaffold dev
----

この状態でskaffoldが待機状態になる。
ためしにこの状態で app/main.nim を更新してみると、自動でコンテナが再ビルドされる
ことが確認できる。

.クラスタの状態確認と、起動しているPodsへの疎通確認
[source,bash]
----
task check
----

クラスタに適用した各種リソースは、 `skaffold dev` を停止するときに自動で削除され
るはずだが、削除されなかった場合は以下のコマンドで後始末できる。

.クラスタに作った各種リソースの削除
[source,bash]
----
task k8s:clear
----
