= 06_skaffold
:toc: left
:sectnums:

活発に開発をしていると、アプリを修正してコンテナを再ビルドして適用を何度も手動で
行うのは手間だ。たとえタスクランナーに処理をまとめたとしても、何度も実行するのは
面倒。これらの問題を解消するために https://skaffold.dev/[skaffold] というツール
を導入する。

skaffoldを使うと、ファイルの変更監視が始まり、ファイルの更新の都度コンテナイメー
ジを再ビルドしてKubernetesクラスタに適用してくれるようになる。また、skaffoldを
Ctrl-Cで停止すると自動で作成された各種リソースを破棄してくれるので、後始末のこと
も考えなくて良くなる。

また、skaffoldは様々なKubernetesのツールをサポートしており、Helmもまたサポートし
ている。

ただし、単純にSkaffoldを入れるだけだと、ビルドされたイメージを使ってくれないため、
設定の微修正が必要。具体的にはhelmのvalues.yamlに、使うイメージ名を設定できるようにする。
そしてskaffoldのartifactOverridesで、helmのvalues.yamlのイメージ名を上書きできるようにする。
この時、artifactOverridesのイメージ名にタグ名を書かないようにすること。

https://skaffold.dev/docs/pipeline-stages/deployers/helm/

`skaffold dev` をTaskfile.ymlに書こうかと思ったけれど、
どうもgo-taskを経由するとCtrl-Cで実行してる タスクを停止したときに、
うまくシグナルがskaffoldに伝わらないらしく、
skaffoldが自動でやってくれるリソースの後始末をやってくれなかった。
よって、しかたなく `skaffold dev` はTaskには定義せずに手打ちすることとした。

== 用語

=== Skaffold

Googleが提供するKubernetes用のビルド・デプロイ自動化ツール。

https://github.com/GoogleContainerTools/skaffold

== 構成

|======
| ディレクトリ | 説明
| app | シンプルなGoのWebサーバ。1234ポートをlistenする
| internal-api | 内部API。1235ポートをlistenする
| k8s | HelmのChartディレクトリ
|======

== 動作方法

taskコマンドを使ってKubernetesを操作します。
処理内容についてはTaskfile.ymlを見てください。

.appコンテナのビルドとKubernetesクラスタへの適用
[source,bash]
----
skaffold dev
----

この状態でskaffoldが待機状態になる。
ためしにこの状態で app/main.nim を更新してみると、自動でコンテナが再ビルドされる
ことが確認できる。

.クラスタの状態確認と、起動しているPodsへの疎通確認
[source,bash]
----
task check
----

クラスタに適用した各種リソースは、 `skaffold dev` を停止するときに自動で削除され
るはずだが、削除されなかった場合は以下のコマンドで後始末できる。

.クラスタに作った各種リソースの削除
[source,bash]
----
task k8s:clear
----
