version: '3'

vars:
  NAMESPACE: local
  HELM_VERSION: v3.5.0

tasks:
  setup:
    desc: "必要な外部コマンドをインストールする"
    cmds:
      - task: setup:helm
      - task: setup:skaffold

  setup:helm:
    desc: "helmをインストールする"
    dir: /usr/local/src
    cmds:
      - sudo install -m 0755 -o $USER -g $USER -d helm/{{.HELM_VERSION}}
      - |
        set -eu

        cd helm/{{.HELM_VERSION}}
        wget https://get.helm.sh/helm-{{.HELM_VERSION}}-linux-amd64.tar.gz
        tar xzf helm-{{.HELM_VERSION}}-linux-amd64.tar.gz
        chmod +x linux-amd64/helm
        sudo ln -sfn $PWD/linux-amd64/helm /usr/local/bin/helm
    status:
      - which helm

  setup:skaffold:
    desc: "skaffoldをインストールする"
    dir: /tmp
    cmds:
      - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
      - sudo install -m 0755 skaffold /usr/local/bin/
    status:
      - which skaffold

  k8s:get:all:
    desc: "名前空間配下のすべてのリソースを表示する"
    cmds:
      - kubectl get all -n {{.NAMESPACE}}

  helm:setup:
    desc: "helmのリポジトリをセットアップする"
    cmds:
      - helm repo add loki https://grafana.github.io/loki/charts
      - helm repo update

  helm:create:monitoring:
    desc: "monitoring chartを生成する"
    cmds:
      - test -d monitoring && rm -rf monitoring
      - helm create monitoring
      - helm inspect chart loki/loki-stack > monitoring/Chart.yaml
      - helm inspect values loki/loki-stack > monitoring/values.yaml
      - rm -rf monitoring/templates/*
      - touch monitoring/templates/.gitkeep

  helm:inspect:loki:
    desc: "lokiのyaml情報を確認する"
    cmds:
      - helm inspect chart loki/loki-stack

  check:
    desc: "Podsとの疎通確認を行う"
    cmds:
      - kubectl get pods -n {{.NAMESPACE}}
      - curl http://localhost:30001
