version: '3'

vars:
  NAMESPACE: local
  HELM_VERSION: v3.5.0

tasks:
  setup:
    desc: "必要な外部コマンドをインストールする"
    cmds:
      - task: setup:helm
      - task: setup:skaffold

  setup:helm:
    desc: "helmをインストールする"
    dir: /usr/local/src
    cmds:
      - sudo install -m 0755 -o $USER -g $USER -d helm/{{.HELM_VERSION}}
      - |
        set -eu

        cd helm/{{.HELM_VERSION}}
        wget https://get.helm.sh/helm-{{.HELM_VERSION}}-linux-amd64.tar.gz
        tar xzf helm-{{.HELM_VERSION}}-linux-amd64.tar.gz
        chmod +x linux-amd64/helm
        sudo ln -sfn $PWD/linux-amd64/helm /usr/local/bin/helm
    status:
      - which helm

  setup:skaffold:
    desc: "skaffoldをインストールする"
    dir: /tmp
    cmds:
      - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
      - sudo install -m 0755 skaffold /usr/local/bin/
    status:
      - which skaffold

  k8s:get:all:
    desc: "名前空間配下のすべてのリソースを表示する"
    cmds:
      - kubectl get all -n {{.NAMESPACE}}

  helm:setup:
    desc: "helmのリポジトリをセットアップする"
    cmds:
      - helm repo add loki https://grafana.github.io/loki/charts
      - helm repo update

  helm:create:
    desc: "chartを生成するタスク"
    cmds:
      - test ! "{{.CHART}}" = "" # Validation
      - test ! "{{.BASE_CHART}}" = "" # Validation
      - test -d {{.CHART}} && rm -rf {{.CHART}}
      - helm create {{.CHART}}
      - helm inspect chart {{.BASE_CHART}} > {{.CHART}}/Chart.yaml
      - helm inspect values {{.BASE_CHART}} > {{.CHART}}/values.yaml
      - rm -rf {{.CHART}}/templates/*
      - touch {{.CHART}}/templates/.gitkeep

  helm:create:loki:
    desc: "loki chartを生成する"
    cmds:
      - task: helm:create
        vars:
          CHART: loki
          BASE_CHART: loki/loki-stack

  helm:inspect:loki:
    desc: "lokiのyaml情報を確認する"
    cmds:
      - helm inspect chart loki/loki-stack

  check:
    desc: "Podsとの疎通確認を行う"
    cmds:
      - kubectl get pods -n {{.NAMESPACE}}
      - curl http://localhost:30001
